version: "3"
services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports: 
      - '82:3000'
    links:
      - mongo  
  mongo:
    image: mongo
    ports: 
      - '27017:27017'